server:
  port: 8090
spring:
  config:
    import:
      - classpath:auth-users.yml
      - optional:configserver:http://localhost:9888
  application:
    name: auth-service
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    "[org.springframework.security]": INFO
