spring:
  kafka:
    bootstrap-servers: localhost:9092

employee:
  es:
    index: employee
    source-url: http://localhost:9210/internal/es/employees
    embedding-field: embedding
  kafka:
    change-topic: employee-change-topic
    es-sync-group: employee-es-sync-group
  embedding:
    provider: bge
    base-url: ${ai.provider.embedding.bge.base-url}
    api-key: ${ai.provider.embedding.bge.api-key}
    model: ${ai.provider.embedding.bge.model}
    dims: ${ai.provider.embedding.bge.dimension}
