spring:
  elasticsearch:
    uris: http://127.0.0.1:9200
#    username: elastic
#    password: your_password
    connection-timeout: 3s
    socket-timeout: 10s

es:
  query:
    total-hits-threshold: 10000
    rebuild-source-allowed-hosts: [localhost, employee-service]
    rebuild-max-batch-size: 500
    management-service-token: ${ES_QUERY_MANAGEMENT_SERVICE_TOKEN:}
