server:
  port: 9201

spring:
  application:
    name: es-query-service
  config:
    import: optional:configserver:http://localhost:9888
  profiles:
    active: datasource,es

es:
  query:
    knowledge:
      enabled: false
