from enum import StrEnum


class DataClassification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    RESTRICTED = "RESTRICTED"
    UNKNOWN = "UNKNOWN"


class SinkPurpose(StrEnum):
    PLANNING = "PLANNING"
    DELEGATED_CALL = "DELEGATED_CALL"
    DOCUMENT_GENERATION = "DOCUMENT_GENERATION"
    FINAL_RESULT = "FINAL_RESULT"
    AUDIT = "AUDIT"


class DelegatedCallTarget(StrEnum):
    SEARCH = "SEARCH"
    EMPLOYEE_QUERY = "EMPLOYEE_QUERY"


class AuditMode(StrEnum):
    LOCAL_ACCEPTED = "LOCAL_ACCEPTED"
    PRE_RELEASE_DURABLE = "PRE_RELEASE_DURABLE"
