eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        ip-address: 127.0.0.1
        prefer-ip-address: true # 注册为 IP，避免 hostname 解析错误
        lease-renewal-interval-in-seconds: 5 # 心跳间隔
        lease-expiration-duration-in-seconds: 15 # 服务过期时间
server:
    port: 8888
spring:
    application:
        name: gateway
    cloud:
        config:
          enabled: false
        gateway:
          server:
            webflux:
             discovery:
                locator:
                    enabled: true # 自动创建基于 Eureka 的路由
                    lower-case-service-id: true
        loadbalancer:
            retry:
                enabled: true