server:
  port: 9100

spring:
  application:
    name: workflow-service
  config:
    import: optional:configserver:http://localhost:9888
  profiles:
    active: datasource,kafka

workflow:
  action:
    dispatchers:
      - log
      - kafka
    topic: workflow-action-@-topic
    outbox-retry-delay-ms: 5000
