CREATE TABLE document_index_rebuild_task (
    task_id VARCHAR(64) PRIMARY KEY,
    domain_name VARCHAR(128) NOT NULL,
    material_type VARCHAR(128) NOT NULL,
    idempotency_digest CHAR(64) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    source_connector_id VARCHAR(128) NOT NULL,
    source_snapshot_id VARCHAR(128) NOT NULL,
    source_snapshot_version VARCHAR(64) NOT NULL,
    source_snapshot_digest CHAR(64) NOT NULL,
    schema_name VARCHAR(128) NOT NULL,
    schema_version VARCHAR(64) NOT NULL,
    schema_digest CHAR(64) NOT NULL,
    target_physical_index_safe_ref VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    expected_document_count BIGINT NULL,
    documents_read BIGINT NOT NULL DEFAULT 0,
    chunks_indexed BIGINT NOT NULL DEFAULT 0,
    bulk_attempts BIGINT NOT NULL DEFAULT 0,
    protected_cursor VARBINARY(4096) NULL,
    manifest_digest CHAR(64) NULL,
    content_digest CHAR(64) NULL,
    failure_code VARCHAR(64) NULL,
    diagnostic_id VARCHAR(128) NULL,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at TIMESTAMP(6) NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    started_at TIMESTAMP(6) NULL,
    heartbeat_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    UNIQUE KEY uk_document_rebuild_idempotency (idempotency_digest),
    UNIQUE KEY uk_document_rebuild_target (target_physical_index_safe_ref),
    KEY idx_document_rebuild_recovery (status, lease_expires_at),
    KEY idx_document_rebuild_corpus (domain_name, material_type, created_at)
);
