# generated by datamodel-codegen:
#   filename:  agent-runtime-openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Capability(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ContractMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability]
    contract_fingerprint: Annotated[
        str, Field(alias='contractFingerprint', pattern='^sha256:[a-f0-9]{64}$')
    ]
    contract_version: Annotated[
        str,
        Field(
            alias='contractVersion',
            pattern='^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$',
        ),
    ]


class Code(StrEnum):
    contract_fingerprint_mismatch = 'CONTRACT_FINGERPRINT_MISMATCH'
    contract_payload_invalid = 'CONTRACT_PAYLOAD_INVALID'
    contract_version_unsupported = 'CONTRACT_VERSION_UNSUPPORTED'
    deadline_exceeded = 'DEADLINE_EXCEEDED'
    runtime_cancelled = 'RUNTIME_CANCELLED'
    runtime_capability_unavailable = 'RUNTIME_CAPABILITY_UNAVAILABLE'
    runtime_contract_incompatible = 'RUNTIME_CONTRACT_INCOMPATIBLE'
    runtime_internal_error = 'RUNTIME_INTERNAL_ERROR'


class RuntimeError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=1)] = None
    code: Code
    contract_fingerprint: Annotated[
        str, Field(alias='contractFingerprint', pattern='^sha256:[a-f0-9]{64}$')
    ]
    contract_version: Annotated[
        str,
        Field(
            alias='contractVersion',
            pattern='^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$',
        ),
    ]
    diagnostic_id: Annotated[
        str,
        Field(
            alias='diagnosticId',
            max_length=128,
            min_length=8,
            pattern='^[A-Za-z0-9_-]+$',
        ),
    ]
    execution_id: Annotated[str | None, Field(alias='executionId', min_length=1)] = None
    message: Annotated[str, Field(max_length=256, min_length=1)]
    request_id: Annotated[str | None, Field(alias='requestId', min_length=1)] = None


class Reason(StrEnum):
    contract_capability_inconsistent = 'CONTRACT_CAPABILITY_INCONSISTENT'
    contract_metadata_invalid = 'CONTRACT_METADATA_INVALID'
    contract_model_load_failed = 'CONTRACT_MODEL_LOAD_FAILED'


class Status(StrEnum):
    contract_not_ready = 'CONTRACT_NOT_READY'
    contract_ready = 'CONTRACT_READY'


class RuntimeReadiness(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: ContractMetadata
    reasons: list[Reason]
    status: Status
