server:
  port: 9210

spring:
  application:
    name: employee-service
  config:
    import: optional:configserver:http://localhost:9888
  profiles:
    active: datasource,emp,ai-provider,kafka

workflow:
  action:
    topic: workflow-action-employee-topic

employee:
  approval:
    mode: workflow
  workflow:
    action-group: employee-workflow-action-group
    inbox-retry-delay-ms: 5000
