server:
  port: 8183
spring:
  application:
    name: mq-consumer-service
  config:
    import: optional:configserver:http://localhost:9888
  profiles:
    active: redis,datasource,kafka,rocketmq
#    datasource:
#      url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=Asia/Shanghai&allowMultiQueries=true
#      username: root
#      password: admin
#      driver-class-name: com.mysql.jdbc.Driver
  kafka:
    producer:
      retries: 3
      acks: all
#            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-consumer-group
      enable-auto-commit: false # 手动提交 offset，保证幂等
      auto-offset-reset: earliest # 消费器重启时从最早位置开始
      max-poll-records: 100 # 批量拉取大小
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#        properties:
#          spring.json.value.default.type: com.example.demo.model.Order  # 反序列化类型
rocketmq:
  producer:
    group: stock-producer-group
  consumer:
    group: stock-consumer-group
