package com.dylan.agent.lifecycle.model;

/**
 * 内部安全错误码枚举，由 D02_02 唯一负责。
 * D03 Entry 层以穷尽 switch 映射到 Agent API AgentErrorCode。
 */
public enum KernelErrorCode {
    PROFILE_INVALID,
    POLICY_INVALID,
    PERMISSION_UNAVAILABLE,
    AUTH_EVIDENCE_CHANGED,
    AUTHORIZATION_REVOKED,
    CATALOG_INCONSISTENT,
    RUNTIME_CONTRACT_INVALID,
    RUNTIME_AUTHENTICATION_FAILED,
    RUNTIME_OUTPUT_INVALID,
    RUNTIME_UNAVAILABLE,
    REGISTRATION_MISMATCH,
    CONTEXT_REQUIRED_MISSING,
    CONTEXT_DECRYPT_FAILED,
    CONTEXT_STALE,
    CONTEXT_WRITE_CONFLICT,
    DOMAIN_BINDING_UNAVAILABLE,
    PLAN_VALIDATION_FAILED,
    HANDLER_FAILED,
    DOWNSTREAM_FAILED,
    OUTPUT_INVALID,
    RESULT_SECURITY_FAILED,
    PERSISTENCE_FAILED,
    DEADLINE_EXCEEDED,
    CANCELLED,
    INTERNAL_ERROR
}
