eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true # 注册为 IP，避免 hostname 解析错误
        lease-renewal-interval-in-seconds: 5 # 心跳间隔
        lease-expiration-duration-in-seconds: 15 # 服务过期时间
server:
    port: 8080
spring:
    cloud:
        config:
            enabled: false
    application:
        name: mserver
#    security:
#        oauth2:
#            resourceserver:
#                jwt:
#                    issuer-uri: http://localhost:8090
