package com.dylan.esquery.document.governance.emergency;

public enum DocumentEmergencyGateVerificationCode {
    VERIFIED, MALFORMED, UNSUPPORTED_CONTRACT, ALGORITHM_NOT_ALLOWED, KEY_NOT_TRUSTED,
    SIGNATURE_INVALID, NOT_YET_VALID, EXPIRED, ROLLOUT_BINDING_MISMATCH,
    TARGET_SET_MISMATCH, STATUS_BLOCKED, STATUS_FAILURE
}
